### ISSUE TITLE
Profile Bug Tracking Issue

### ISSUE THREAD

**Issue by NyCodeGHG** [DRSchlaubi/mikbot#36]
- [x] GitHub Profile url links to API
- [x] Pronoun Slash Command Arguments use translation keys
- [ ] Admin Commands for giving badges to users
- [ ] Profiles should look good on mobile
- [x] "Pronouns" in profile not translated to german
- [x] profile picture missing in profile
- [ ] Use read_connections scope to add other account links
- [x] Add profile data to gdpr
- [ ] Add profile visibilty options

**Comment by DRSchlaubi** [comment]
>  Profiles should look good on mobile
Very descriptive

**Comment by NyCodeGHG** [comment]
![Screenshot_20211205-215652](https://user-images.githubusercontent.com/37078297/144763657-0cbc5586-4e96-4e87-9dce-4a28fb4e3f82.png)
This looks a bit ugly

**Comment by DRSchlaubi** [comment]
tf
